[Application Options]
alias=coinos-lnd
restlisten=0.0.0.0:8080
tlsextradomain=lnd
accept-keysend=true

[protocol]
protocol.wumbo-channels=true

[Bitcoin]
bitcoin.regtest=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bc:18443
bitcoind.rpcuser=admin1
bitcoind.rpcpass=123
bitcoind.zmqpubrawblock=tcp://bc:18506
bitcoind.zmqpubrawtx=tcp://bc:18507
