##
## strfry relay config
##

relay {
    bind = "0.0.0.0"
    port = 7777

    nofiles = 0

    realIpHeader = ""

    db = "/app/strfry-db"

    dbParams {
        maxreaders = 256
        mapsize = 10995116277760
    }

    nostrSigning {
        enabled = false
    }

    info {
        name = "coinos relay"
        description = "Local strfry relay for coinos"
        pubkey = ""
        contact = ""
    }

    maxFilterLimit = 500
    maxSubsPerConnection = 20

    writePolicy {
        plugin = ""
    }

    compression {
        enabled = true
    }

    logging {
        dumpInAll = false
        dumpInEvents = false
        dumpInReqs = false
        dbScanPerf = false
    }

    numThreads {
        ingester = 3
        reqWorker = 3
        reqMonitor = 1
        negentropy = 2
    }
}
